version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel -r requirements.txt .
      - pip install --upgrade --pre jsonschema
  build:
    commands:
      - set "setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/" && export files="$@"
      - printf '%s\n' "$files" | xargs printf '<%s>\n'
      - ./json_lint --check
      - ./newline_lint --check
      - isort --check-only --verbose --recursive "$@"
      - black --check "$@"
      - flake8 "$@"
      - pylint "$@"
      - bandit -r "src/" --exclude "tests"
      - pytest --cov="src/" --doctest-modules "src/" "tests/"
