version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel -r requirements.txt .
      - pip install --upgrade --pre jsonschema
  build:
    commands:
      - ./json_lint --check
      - ./newline_lint --check
      - isort --check-only --verbose --recursive "setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/"
      - black --check "setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/"
      - flake8 "setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/"
      - pylint "setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/"
      - bandit -r "src/" --exclude "tests"
      - pytest --cov="src/" --doctest-modules "src/" "tests/"
