version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel -r requirements.txt .
      - pip install --upgrade --pre jsonschema
  build:
    commands:
      - isort --check-only --verbose --recursive "setup.py" "run_lint" "uluru/" "tests/"
      - black --check "setup.py" "run_lint" "uluru/" "tests/"
      - flake8 "setup.py" "run_lint" "uluru/" "tests/"
      - pylint "setup.py" "run_lint" "uluru/" "tests/"
      - bandit -r "uluru/" --exclude "tests"
      - pytest --cov="uluru/" --doctest-modules "uluru/" "tests/"
