version: 0.2
phases:
  pre_build:
    commands:
      - pip install --upgrade pip wheel -r requirements.txt .
      - pip install --upgrade --pre jsonschema
  build:
    commands:
      - declare -a files=("setup.py" "run_lint" "json_lint" "newline_lint" "src/" "tests/")
      - ./json_lint --check
      - ./newline_lint --check
      - isort --check-only --verbose --recursive "${files[@]}"
      - black --check "${files[@]}"
      - flake8 "${files[@]}"
      - pylint "${files[@]}"
      - bandit -r "src/" --exclude "tests"
      - pytest --cov="src/" --doctest-modules "src/" "tests/"
