on:
  push:
    branches: [ master ]

  workflow_dispatch: # Enables on-demand/manual triggering: https://docs.github.com/en/free-pro-team@latest/actions/managing-workflow-runs/manually-running-a-workflow
jobs:
  contract-integration-java:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: aws-cloudformation/aws-cloudformation-resource-providers-lookoutvision
          path: lookoutvision
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu'  # match distribution for v1
          java-version: 8
      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: 'pip'
      - run: |
          pip install -e .
          cd lookoutvision/*project
          curl -s -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam.zip
          unzip -q sam.zip -d sam-install
          sudo ./sam-install/install --update
          sam local start-lambda &
          pip install --quiet cloudformation-cli-java-plugin cloudformation-cli-python-plugin
          mvn package --no-transfer-progress -Dmaven.test.skip=true
          cfn test --enforce-timeout 240 -vvv
          ! grep -q -E -i '(accessKeyId|secretAccessKey|sessionToken)' rpdk.log*
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
  contract-integration-python:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: aws-cloudformation/aws-cloudformation-resource-providers-frauddetector
          path: frauddetector
      - uses: actions/setup-python@v4
        with:
          python-version: 3
          cache: 'pip'
      - run: |
          pip install -e .
          cd frauddetector/*outcome
          curl -s -L https://github.com/aws/aws-sam-cli/releases/latest/download/aws-sam-cli-linux-x86_64.zip -o sam.zip
          unzip -q sam.zip -d sam-install
          sudo ./sam-install/install --update
          sam local start-lambda &
          pip install --quiet cloudformation-cli-java-plugin cloudformation-cli-python-plugin
          cfn submit --dry-run
          cfn test --enforce-timeout 240 -vvv
          ! grep -q -E -i '(accessKeyId|secretAccessKey|sessionToken)' rpdk.log*
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: us-east-1
